// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token, user_id, expires_at, revoked_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
returning token, user_id, revoked_at, expires_at, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireRefreshToken = `-- name: ExpireRefreshToken :execrows
UPDATE refresh_tokens
SET expires_at = $1, updated_at = $2
WHERE 
  token = $3
  AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
`

type ExpireRefreshTokenParams struct {
	ExpiresAt time.Time
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) ExpireRefreshToken(ctx context.Context, arg ExpireRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, expireRefreshToken, arg.ExpiresAt, arg.UpdatedAt, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findRefreshToken = `-- name: FindRefreshToken :one
SELECT rt.token, rt.user_id, rt.revoked_at, rt.expires_at, rt.created_at, rt.updated_at
FROM refresh_tokens rt
INNER JOIN users u ON u.id = rt.user_id
WHERE token = $1
LIMIT 1
`

func (q *Queries) FindRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, findRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens 
SET revoked_at = $1, updated_at = $2 
WHERE 
  token = $3 
  AND revoked_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
`

type RevokeRefreshTokenParams struct {
	RevokedAt sql.NullTime
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.RevokedAt, arg.UpdatedAt, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
